export const guru_token = Cypress.env('guru_token')
export const freetour_login = Cypress.env('freetour_login')
export const freetour_pass = Cypress.env('freetour_pass')
export const bokun_login = Cypress.env('bokun_login')
export const bokun_pass = Cypress.env('bokun_pass')
